shortlinks/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('about/', views.about, name='about'),
    path('links/', views.LinksView.as_view(), name='links'),
]

shortlinks/shortlinks/urls.py
from shortlinks import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shortlinks/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-reset/',
         PasswordResetView.as_view(template_name = "users/password_reset_form.html",
                                   email_template_name='users/password_reset_form.html',
                                   success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                                                              success_url=reverse_lazy("users:password_reset_complete")), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

shortlinks/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'main/css/styles.css' %}" rel="stylesheet" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <header>
        <div class="all-header">
            <div class="logo-container">
                <div class="logo"></div>
                <p>Уберем все лишнее из ссылки</p>
            </div>

            <div class="navigation">
                <a href="{% url 'home' %}">Главная</a>
                <a href="{% url 'about' %}">Про нас</a>
                <a href="{% url 'contact' %}">Связаться с нами</a>
                {% if user.is_authenticated %}
                <a href="{% url 'links' %}">Ссылки</a>
               <button> <a href="{% url 'users:profile' %}">Профиль</a></button>
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit">Выйти</button>
                </form>
                {% else %}
                <button><a href="{% url 'users:login' %}">Войти</a></button>
                <button><a href="{% url 'users:register' %}">Регистрация</a></button>
                {% endif %}
            </div>
        </div>
    </header>

    <main>
            <!-- Блок контента -->
        <div class="content-container">
            {% block content %}
            {% endblock %}
        </div>
        <!-- Конец блока контента -->

    </main>

    <footer>
        <div class="footer-container">
            <div class="prava">
                <span>Все права защищены &copy;</span>
            </div>

            <div class="links-footer">
                <a href="#"><div id="twitter"></div></a>
                <a href="https://vk.com/"><div id="vk"></div></a>
                <a href="https://youtube.com/"><div id="youtube"></div></a>
                <a href="https://web.telegram.org/"><div id="telegram"></div></a>
            </div>
        </div>
    </footer>
</body>
</html>